[package]
name = "hnm"
version = "0.1.0"
authors = ["HoshinoTented <limbolrain@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "5.1.2"
pest = "2.1"
pest_derive = "2.1"
lazy_static = "1.4.0"